### ISSUE TITLE
ensenso_bridge fails in Ubuntu 14.04 if Beignet is installed

### ISSUE THREAD

**Issue by rsthomp** [lakehanne/ensenso#2]
After building and compiling, running ensenso_bridge resulted in this error:
`DRM_IOCTL_I915_GEM_APERTURE failed: Invalid argument
Assuming 131072kB available aperture size.
May lead to reduced performance or incorrect rendering.
get chip id failed: -1 [22]
param: 4, val: 0
Segmentation fault (core dumped)
`
Removing the Beignet OpenCL package resolves the problem. Might be useful info to include in the README.

**Comment by lakehanne** [comment]
I started having the same problem on my newly minted ubuntu 14.04.

What's the command you used to remove opencl?

**Comment by robotsorcerer** [comment]
Looks like it has to do with a user not being a part of the video group. Next time when this occurs, you can do `ls -l /dev/dri/`  to check if you are not a member of the video group. If you are not, you can add yourself as follows:

```bash
sudo usermod -aG video $USER
```

If things are still not honky-dory, perhaps, you could try installing `ocl-icd-opencl-dev`. This is packaged on the following PPA and you can install like so:

```bash
sudo apt-add-repository ppa:floe/beignet; sudo apt-get update; sudo apt-get install beignet-dev; sudo dpkg -i debs/ocl-icd*deb
```
